# Site settings
title: Only Two Hard Problems
email: chris@onlytwo.io
description: >-
  Bootstrapping software for startups

baseurl: "/"
url: "https://onlytwo.io"

twitter_username: chrisapplegate
github_username:  chrisapplegate
linkedin_username: chrisapplegate

# Build settings
markdown: kramdown
theme: minima

google_analytics: UA-133794117-1
