# Site settings
title: Chris Applegate
email: chris@onlytwo.io
description: >-
  Contract CTO/Lead Developer

baseurl: "/"
url: "https://onlytwo.io"

twitter_username: chrisapplegate
github_username:  chrisapplegate
linkedin_username: chrisapplegate

# Build settings
markdown: kramdown
theme: minima

google_analytics: UA-133794117-1
